export default {digital: [
    {
        source: '../images/Digital/gl1.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl2.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl3.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl4.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl5.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl6.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl7.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl8.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl9.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl10.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl11.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl12.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl13.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl14.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl15.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl16.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl17.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl18.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl19.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl20.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl21.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl22.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl23.jpg',
        caption: 'Hello'
    },   {
        source: '../images/Digital/gl24.jpg',
        caption: 'Hello'
    },
],

graphic: [
    {
        source: '../images/Graphic/gl1.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl2.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl3.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl4.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl5.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl6.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl7.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl8.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl9.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl10.jpg',
        caption: 'hi'
    },   {
        source: '../images/Graphic/gl11.jpg',
        caption: 'hi'
    },  {
        source: '../images/Graphic/gl12.jpg',
        caption: 'hi'
    }, 
]}
